# This file is automatically generated by pyo3_stub_gen
# ruff: noqa: E501, F401, F403, F405

import builtins
import numpy
import numpy.typing
import typing
__all__ = [
    "CoefficientTruncator",
    "FrequencyTruncationPolicy",
    "FrequencyTruncator",
    "GateNoiseModel",
    "Logger",
    "MajoranaMonomial",
    "MajoranaPropagator",
    "MajoranaSurrogateModel",
    "MajoranaSurrogatePropagator",
    "MajoranaTermStreamer",
    "MajoranaTermSum",
    "MonomialBudget",
    "NativeNoiseModel",
    "NativeTruncator",
    "PauliPropagator",
    "PauliString",
    "PauliSurrogateModel",
    "PauliSurrogatePropagator",
    "PauliTermStreamer",
    "PauliTermSum",
    "PropagationResult",
    "Simplify",
    "TermBudget",
    "TruncationPolicy",
    "UniformNoiseModel",
    "WeightTruncator",
    "hybrid_expectation",
    "rust_available",
]

class CoefficientTruncator:
    @property
    def coefficient(self) -> typing.Optional[builtins.float]: ...
    @coefficient.setter
    def coefficient(self, value: typing.Optional[builtins.float]) -> None: ...
    def __new__(cls, coefficient: typing.Optional[builtins.float] = None) -> CoefficientTruncator: ...
    def __repr__(self) -> builtins.str: ...

@typing.final
class FrequencyTruncationPolicy:
    @property
    def max_frequency(self) -> typing.Optional[builtins.int]:
        r"""
        Drop monomials with more than this many trig factors (None = no limit).
        """
    @max_frequency.setter
    def max_frequency(self, value: typing.Optional[builtins.int]) -> None:
        r"""
        Drop monomials with more than this many trig factors (None = no limit).
        """
    @property
    def weight_cutoff(self) -> typing.Optional[builtins.int]:
        r"""
        Drop Pauli/Majorana terms with weight exceeding this value (None = no limit).
        """
    @weight_cutoff.setter
    def weight_cutoff(self, value: typing.Optional[builtins.int]) -> None:
        r"""
        Drop Pauli/Majorana terms with weight exceeding this value (None = no limit).
        """
    @property
    def truncation_range(self) -> tuple[typing.Optional[builtins.int], typing.Optional[builtins.int]]:
        r"""
        The (min_terms, max_terms) pair controlling when and how aggressively truncation fires.
        """
    @truncation_range.setter
    def truncation_range(self, value: tuple[typing.Optional[builtins.int], typing.Optional[builtins.int]]) -> None: ...
    def __new__(cls, max_frequency: typing.Optional[builtins.int] = None, weight_cutoff: typing.Optional[builtins.int] = None, truncation_range: typing.Optional[tuple[typing.Optional[builtins.int], typing.Optional[builtins.int]]] = None) -> FrequencyTruncationPolicy: ...
    def __repr__(self) -> builtins.str: ...

class FrequencyTruncator:
    @property
    def frequency(self) -> typing.Optional[builtins.int]: ...
    @frequency.setter
    def frequency(self, value: typing.Optional[builtins.int]) -> None: ...
    def __new__(cls, frequency: typing.Optional[builtins.int] = None) -> FrequencyTruncator: ...
    def __repr__(self) -> builtins.str: ...

class GateNoiseModel:
    r"""
    Noise model that delegates to an inner Python object's damping_factor and apply_noise.
    
    Arguments:
        inner: Python object exposing damping_factor(weight, active_modes) -> float
               and apply_noise(term_sum) methods.
    """
    @property
    def inner(self) -> typing.Any:
        r"""
        The wrapped Python noise model object.
        """
    def __new__(cls, inner: typing.Any) -> GateNoiseModel:
        r"""
        Initialize the gate noise model wrapping a custom Python noise object.
        
        Arguments:
            inner: Python object providing `damping_factor(weight, active_modes) -> float`
                   and `apply_noise(term_sum)` methods.
        """
    def damping_factor(self, term_weight: builtins.int, active_modes: builtins.int) -> builtins.float:
        r"""
        Delegate to the wrapped model's `damping_factor` method.
        """
    def damping_factor_term(self, basis_kind: builtins.int, words: typing.Sequence[builtins.int], n_units: builtins.int, weight: builtins.int) -> builtins.float:
        r"""
        Delegate to the wrapped model's `damping_factor_term` method.
        
        Only meaningful for a wrapped object that defines one; propagation
        unwraps this model and calls the inner object directly, so this exists
        for symmetry with `damping_factor` rather than as the hot path.
        
        Arguments:
            basis_kind: 0 for Pauli, 1 for Majorana.
            words: The term's raw basis-string words, two bits per unit.
            n_units: Qubits (Pauli) or modes (Majorana) of the register.
            weight: The term's weight.
        """
    def apply_noise(self, term_sum: typing.Any) -> None:
        r"""
        Delegate to the wrapped model's `apply_noise` method.
        """

@typing.final
class Logger:
    r"""
    Structured event logger for propagator runs, writing JSON Lines to a file.
    
    Arguments:
        filename: Path to write the JSON Lines event log.
        log_every: Emit a gate-event record every N gate applications (default 1).
    """
    @property
    def filename(self) -> builtins.str: ...
    @property
    def log_every(self) -> builtins.int: ...
    def __new__(cls, filename: builtins.str, log_every: builtins.int = 1) -> Logger:
        r"""
        Configure verbose logging for a propagator run.
        
        Events are written as JSON Lines to *filename*. Each gate application
        and truncation step produces one record.
        
        Arguments:
            filename: Path to write the JSON Lines event log.
            log_every: Emit a gate-event record every N gate applications (default 1).
        """

@typing.final
class MajoranaMonomial:
    r"""
    A Majorana monomial, a product of Majorana operators encoded as a mode bitmask.
    
    Bit 2k is set if $\gamma_{2k}$ (even mode) is active on site k.
    Bit 2k+1 is set if $\gamma_{2k+1}$ (odd mode) is active on site k.
    
    Arguments:
        modes: Integer bitmask encoding occupied Majorana modes.
        n_modes: Total number of Majorana modes (must be even, equal to 2 * n_qubits).
        is_number_preserving: Whether the monomial preserves particle number (default True).
    """
    @property
    def n_modes(self) -> builtins.int:
        r"""
        The number of Majorana modes in the system
        """
    @property
    def is_number_preserving(self) -> builtins.bool:
        r"""
        Whether or not the monomial preserves particle number (i.e. fully paired).
        """
    @property
    def modes(self) -> typing.Any:
        r"""
        The active mode indices as a Python integer bitmask.
        """
    @property
    def length(self) -> builtins.int:
        r"""
        Number of active Majorana modes in the monomial (popcount of the mode bitmask).
        """
    @property
    def weight(self) -> builtins.int:
        r"""
        Pauli weight of this monomial under the Jordan-Wigner mapping.
        """
    def __new__(cls, modes: typing.Any, n_modes: builtins.int, is_number_preserving: builtins.bool = True) -> MajoranaMonomial:
        r"""
        Construct a Majorana monomial from a mode bitmask.
        
        Arguments:
            modes: Integer bitmask where bit 2k (2k+1) is set if Majorana mode gamma_{2k} (gamma_{2k+1}) is active.
            n_modes: Total number of Majorana modes (must be even).
            is_number_preserving: Whether the monomial preserves particle number.
        """
    def overlap(self, other: MajoranaMonomial) -> builtins.int:
        r"""
        Number of Majorana modes shared with *other* (popcount of modes & other.modes).
        Arguments:
            other: Another MajoranaMonomial to compare with.
        Returns:
            The number of Majorana modes that are active in both self and other.
        """
    def commutes_with(self, other: MajoranaMonomial) -> builtins.bool:
        r"""
        Return True if this monomial commutes with *other*.
        Arguments:
            other: Another MajoranaMonomial to check commutation with.
        Returns:
            True if self and other commute, False otherwise.
        """
    def resulting_weight(self, other: MajoranaMonomial) -> builtins.int:
        r"""
        Pauli weight of the product monomial self @ other, without computing the full product.
        Arguments:
            other: Another MajoranaMonomial to multiply with.
        Returns:
            The Pauli weight of the resulting monomial from multiplying self and other.
        """
    def __matmul__(self, other: MajoranaMonomial) -> tuple[builtins.complex, MajoranaMonomial]:
        r"""
        Multiply two Majorana monomials, returning (phase, product).
        
        The phase factor accounts for the anticommutation relations of Majorana operators.
        """
    def trace_with_fock_state(self, fock_state: typing.Any) -> builtins.float:
        r"""
        Compute $\langle \psi |M| \psi \rangle$ for this Majorana monomial M.
        
        Returns 0.0 if M has any unpaired modes.
        For paired modes, returns the product of $(2n_k - 1)$ values for each occupied pair.
        
        Arguments:
            fock_state: Computational basis state as a bitstring integer.
        Returns:
            Expectation value of the Majorana monomial in the given Fock state.
        """
    def to_bytes(self) -> bytes:
        r"""
        Serialize the mode bitmask as a little-endian byte string.
        """
    def __hash__(self) -> builtins.int: ...
    def __eq__(self, other: MajoranaMonomial) -> builtins.bool: ...

@typing.final
class MajoranaPropagator:
    r"""
    Back-propagates Majorana observables through quantum circuits in the Heisenberg picture.
    
    Arguments:
        noise: Optional noise model (UniformNoiseModel, GateNoiseModel, or custom).
        truncation: A list of truncators
            (WeightTruncator, CoefficientTruncator, TermBudget), a single such
            truncator, a legacy TruncationPolicy (decomposed), or None. The
            symbolic-only FrequencyTruncator is rejected.
        n_threads: Number of worker threads. Defaults to the system thread count.
        logger: Optional Logger for verbose JSON Lines event logging.
        pin_threads: Bind each worker to its own CPU. On by default, and worth
            8x to 32x on the partitioned engine, because a partition's store fits
            a core's private cache only if the same core keeps serving it.
            **Turn it off when the process also runs threaded BLAS.** A pinned
            worker cannot step around a spinning BLAS thread, and qiskit loads
            two OpenBLAS copies that each start one spinner per core: measured
            449ms against 184ms at 64 threads. Setting OPENBLAS_NUM_THREADS=1
            before numpy imports is the better fix.
    """
    @property
    def noise(self) -> typing.Optional[typing.Any]: ...
    @property
    def truncators(self) -> builtins.list[typing.Any]:
        r"""
        The active truncation pipeline as a list of truncator objects.
        """
    def __new__(cls, noise: typing.Optional[typing.Any] = None, truncation: typing.Optional[typing.Any] = None, n_threads: typing.Optional[builtins.int] = None, logger: typing.Optional[typing.Any] = None, pin_threads: builtins.bool = True) -> MajoranaPropagator:
        r"""
        Initialize the Majorana propagator. See the class docstring for arguments.
        """
    def propagate(self, observable: MajoranaTermSum, circuit: typing.Any, filename: typing.Optional[builtins.str] = None) -> MajoranaTermSum:
        r"""
        Back-propagate *circuit* through *observable*, returning the evolved term sum.
        
        Arguments:
            observable: The Majorana observable to back-propagate.
            circuit: A MajoranaCircuit whose rotations are applied in reverse.
            filename: If given, save the final terms to a gzip-compressed binary file at this path.
        """
    def expectation_value(self, observable: MajoranaTermSum, circuit: typing.Any, initial_state: typing.Optional[typing.Any] = None, filename: typing.Optional[builtins.str] = None) -> PropagationResult:
        r"""
        Compute the expectation value of *observable* in the state prepared by *circuit*.
        
        Arguments:
            observable: The Majorana observable.
            circuit: A MajoranaCircuit applied to the reference state.
            initial_state: Fock state as a bitstring integer.
            filename: If given, save the final terms to a gzip-compressed binary file at this path.
        """
    def set_noise(self, noise: typing.Optional[typing.Any] = None) -> None: ...
    def set_truncation(self, truncation: typing.Optional[typing.Any] = None) -> None:
        r"""
        Replace the truncation pipeline (accepts the same forms as the
        constructor's `truncation`).
        """

@typing.final
class MajoranaSurrogateModel:
    r"""
    Compiled surrogate model for Majorana observables.
    """
    @property
    def n_params(self) -> builtins.int: ...
    @property
    def n_terms(self) -> builtins.int: ...
    @property
    def n_monomials(self) -> builtins.int: ...
    def evaluate(self, params: typing.Sequence[builtins.float]) -> builtins.float:
        r"""
        Evaluate the expectation value. `params[i]` is the angle (radians) for parameter `i`.
        """
    def evaluate_batch(self, param_sets: typing.Sequence[typing.Sequence[builtins.float]]) -> builtins.list[builtins.float]: ...
    def save(self, path: builtins.str) -> None: ...
    @staticmethod
    def load(path: builtins.str) -> MajoranaSurrogateModel: ...
    def __repr__(self) -> builtins.str: ...

@typing.final
class MajoranaSurrogatePropagator:
    r"""
    Back-propagates Majorana observables symbolically.
    """
    @property
    def truncators(self) -> builtins.list[typing.Any]:
        r"""
        The active truncation pipeline as a list of truncator objects.
        """
    def __new__(cls, truncation: typing.Optional[typing.Any] = None, n_threads: typing.Optional[builtins.int] = None, logger: typing.Optional[typing.Any] = None) -> MajoranaSurrogatePropagator: ...
    def build(self, observable: MajoranaTermSum, circuit: typing.Any, initial_state: typing.Optional[typing.Any] = None) -> MajoranaSurrogateModel: ...
    def set_truncation(self, truncation: typing.Optional[typing.Any] = None) -> None:
        r"""
        Replace the truncation pipeline (accepts the same forms as the
        constructor's `truncation`).
        """

@typing.final
class MajoranaTermStreamer:
    @staticmethod
    def from_file(path: builtins.str) -> MajoranaTermStreamer:
        r"""
        Open a gzip-compressed binary file for lazy streaming.
        
        Arguments:
            path: Path to a file written by `MajoranaTermSum.save()`.
        """
    def __iter__(self) -> MajoranaTermStreamer: ...
    def __next__(self) -> typing.Optional[tuple[MajoranaMonomial, builtins.float]]: ...

class MajoranaTermSum:
    r"""
    A mutable, weighted sum of Majorana monomials with real coefficients.
    
    Arguments:
        terms: Optional initial mapping of MajoranaMonomial to real coefficient.
        dtype: Coefficient precision, "float64" (default) or "float32".
    """
    @property
    def dtype(self) -> builtins.str:
        r"""
        Coefficient precision: "float64" or "float32".
        """
    @property
    def sparse_key_bytes(self) -> builtins.int:
        r"""
        Bytes of resident sparse key storage held by this term sum.
        
        Keys only: coefficients and merge metadata are excluded.
        """
    def __new__(cls, terms: typing.Optional[dict] = None, dtype: typing.Optional[builtins.str] = None) -> MajoranaTermSum:
        r"""
        Initialize a Majorana term sum.
        
        Arguments:
            terms: Optional initial mapping of MajoranaMonomial to real coefficient.
            dtype: Coefficient precision, "float64" (default) or "float32".
        """
    def add(self, term: MajoranaMonomial, coeff: builtins.float) -> None:
        r"""
        Add *coeff* * *term* to the sum, accumulating if the monomial is already present.
        """
    def scale(self, factor: builtins.float) -> None:
        r"""
        Multiply every coefficient by *factor* in-place.
        """
    def merge(self, other: MajoranaTermSum) -> None:
        r"""
        Add all terms from *other* into this sum. Both sums must share the same dtype.
        """
    def merge_from_file(self, streamer: MajoranaTermStreamer) -> None:
        r"""
        Stream terms from a file and merge them into this sum one at a time,
        accumulating coefficients for monomials already present. The file is
        always f64; values are cast down if this sum is float32.
        
        Arguments:
            streamer: A MajoranaTermStreamer opened with MajoranaTermStreamer.from_file().
        """
    def truncate(self, policy: typing.Any) -> None:
        r"""
        Deduplicate and remove terms according to *policy*.
        """
    def apply_damping(self, noise: typing.Any, active_modes: builtins.int) -> None:
        r"""
        Apply noise damping to every coefficient.
        """
    def norm_squared(self) -> builtins.float:
        r"""
        Return the sum of |coefficient|^2 over all terms.
        """
    def items(self) -> builtins.list[tuple[MajoranaMonomial, builtins.float]]:
        r"""
        Return all (monomial, coefficient) pairs.
        """
    def __len__(self) -> builtins.int: ...
    def __setitem__(self, term: MajoranaMonomial, coeff: builtins.float) -> None: ...
    def __getitem__(self, term: MajoranaMonomial) -> builtins.float: ...
    def copy(self) -> MajoranaTermSum:
        r"""
        Return a shallow copy of this term sum.
        """
    @staticmethod
    def from_file(path: builtins.str) -> MajoranaTermSum:
        r"""
        Load a MajoranaTermSum from a gzip-compressed binary file saved by `propagate` or
        `expectation_value`. Always loads as float64 (the file format's precision).
        
        Arguments:
            path: Path to the file written by the `filename` parameter.
        """
    def save(self, path: builtins.str) -> None:
        r"""
        Save this term sum to a gzip-compressed binary file. Coefficients are
        always widened to f64 on disk regardless of in-memory precision.
        
        Arguments:
            path: Destination file path.
        """

class MonomialBudget:
    @property
    def max_monomials(self) -> typing.Optional[builtins.int]: ...
    @max_monomials.setter
    def max_monomials(self, value: typing.Optional[builtins.int]) -> None: ...
    @property
    def min_monomials(self) -> typing.Optional[builtins.int]: ...
    @min_monomials.setter
    def min_monomials(self, value: typing.Optional[builtins.int]) -> None: ...
    def __new__(cls, max_monomials: typing.Optional[builtins.int] = None, min_monomials: typing.Optional[builtins.int] = None) -> MonomialBudget: ...
    def __repr__(self) -> builtins.str: ...

class NativeNoiseModel:
    r"""
    Noise model backed by a dynamically loaded native (C/Rust/AOT-Julia)
    plugin.
    
    Arguments:
        path: Filesystem path to the plugin shared library (.so/.dylib/.dll).
        config: Optional JSON string passed once to the plugin's
                `propaq_noise_create`, if it exports one.
    """
    @property
    def abi_version(self) -> builtins.int:
        r"""
        The ABI version the loaded plugin declared, 1 or 2.
        """
    def __new__(cls, path: builtins.str, config: typing.Optional[builtins.str] = None) -> NativeNoiseModel: ...
    def damping_factor(self, term_weight: builtins.int, active_modes: builtins.int) -> builtins.float:
        r"""
        Delegate to the plugin's `propaq_noise_damping_factor`. ABI v1 plugins only.
        """
    def factor_term(self, basis_kind: builtins.int, words: typing.Sequence[builtins.int], n_units: builtins.int, weight: builtins.int) -> builtins.float:
        r"""
        Delegate to the plugin's `propaq_noise_factor_v2`. ABI v2 plugins only.
        
        Exposed so a plugin can be exercised from Python without running a
        circuit; propagation calls the same entry point directly from the pool.
        
        Arguments:
            basis_kind: 0 for Pauli, 1 for Majorana.
            words: The term's raw basis-string words, two bits per unit.
            n_units: Qubits (Pauli) or modes (Majorana) of the register.
            weight: The term's weight.
        """

class NativeTruncator:
    r"""
    Truncation policy backed by a dynamically loaded native (C/Rust/AOT-Julia)
    plugin.
    
    Arguments:
        path: Filesystem path to the plugin shared library (.so/.dylib/.dll).
        config: Optional JSON string passed once to the plugin's
                `propaq_truncator_create`, if it exports one.
    """
    @property
    def abi_version(self) -> builtins.int:
        r"""
        The ABI version the loaded plugin declared, 1 or 2.
        """
    def __new__(cls, path: builtins.str, config: typing.Optional[builtins.str] = None) -> NativeTruncator: ...
    def keep_term(self, term_weight: builtins.int, coeff_magnitude: builtins.float, active_modes: builtins.int) -> builtins.bool: ...
    def keep_term_v2(self, basis_kind: builtins.int, words: typing.Sequence[builtins.int], n_units: builtins.int, weight: builtins.int, coeff_magnitude: builtins.float) -> builtins.bool:
        r"""
        Delegate to the plugin's `propaq_truncator_keep_v2`. ABI v2 plugins only.
        
        Exposed so a plugin can be exercised from Python without running a
        circuit; propagation calls the same entry point directly from the pool.
        
        Arguments:
            basis_kind: 0 for Pauli, 1 for Majorana.
            words: The term's raw basis-string words, two bits per unit.
            n_units: Qubits (Pauli) or modes (Majorana) of the register.
            weight: The term's weight.
            coeff_magnitude: The term's coefficient magnitude.
        """
    def __repr__(self) -> builtins.str: ...

@typing.final
class PauliPropagator:
    r"""
    Back-propagates Pauli observables through quantum circuits in the Heisenberg picture.
    
    Arguments:
        noise: Optional noise model (UniformNoiseModel, GateNoiseModel, or custom).
        truncation: A list of truncators (WeightTruncator, CoefficientTruncator, TermBudget), a single such
            truncator, a legacy TruncationPolicy (decomposed), or None. The
            symbolic-only FrequencyTruncator is rejected.
        n_threads: Number of worker threads. Defaults to the system thread count.
        logger: Optional Logger for verbose JSON Lines event logging.
        pin_threads: Bind each worker to its own CPU. On by default, and worth
            8x to 32x on the partitioned engine, because a partition's store fits
            a core's private cache only if the same core keeps serving it.
            **Turn it off when the process also runs threaded BLAS.** A pinned
            worker cannot step around a spinning BLAS thread, and qiskit loads
            two OpenBLAS copies that each start one spinner per core: measured
            449ms against 184ms at 64 threads. Setting OPENBLAS_NUM_THREADS=1
            before numpy imports is the better fix.
    """
    @property
    def noise(self) -> typing.Optional[typing.Any]:
        r"""
        The noise model used during propagation, if any.
        """
    @property
    def truncators(self) -> builtins.list[typing.Any]:
        r"""
        The active truncation pipeline as a list of truncator objects.
        """
    def __new__(cls, noise: typing.Optional[typing.Any] = None, truncation: typing.Optional[typing.Any] = None, n_threads: typing.Optional[builtins.int] = None, logger: typing.Optional[typing.Any] = None, pin_threads: builtins.bool = True) -> PauliPropagator:
        r"""
        Initialize the Pauli propagator. See the class docstring for arguments.
        """
    def propagate(self, observable: PauliTermSum, circuit: typing.Any, filename: typing.Optional[builtins.str] = None) -> PauliTermSum:
        r"""
        Back-propagate *circuit* through *observable*, returning the evolved term sum.
        
        Arguments:
            observable: The Pauli observable to back-propagate.
            circuit: A PauliCircuit whose rotations are applied in reverse.
            filename: If given, save the final terms to a gzip-compressed binary file at this path.
        """
    def expectation_value(self, observable: PauliTermSum, circuit: typing.Any, initial_state: typing.Optional[typing.Any] = None, filename: typing.Optional[builtins.str] = None) -> PropagationResult:
        r"""
        Compute the expectation value of *observable* in the state prepared by *circuit*.
        
        Arguments:
            observable: The Pauli observable.
            circuit: A PauliCircuit applied to the reference state.
            initial_state: Computational basis reference state as a bitstring integer.
            filename: If given, save the final terms to a gzip-compressed binary file at this path.
        """
    def set_noise(self, noise: typing.Optional[typing.Any] = None) -> None:
        r"""
        Set the noise model for this propagator.
        """
    def set_truncation(self, truncation: typing.Optional[typing.Any] = None) -> None:
        r"""
        Replace the truncation pipeline (accepts the same forms as the
        constructor's `truncation`).
        """

@typing.final
class PauliString:
    r"""
    An n-qubit Pauli operator encoded as two integer bitmasks.
    
    `x` and `z` together encode the single-qubit Pauli on each qubit:
    
    00 -> I, 01 -> X, 10 -> Z, 11 -> Y
    
    Arguments:
        x: Integer bitmask where bit k is set if qubit k has an X or Y component.
        z: Integer bitmask where bit k is set if qubit k has a Z or Y component.
        n_qubits: Total number of qubits in the system.
    """
    @property
    def n_qubits(self) -> builtins.int:
        r"""
        @private
        """
    @property
    def x(self) -> typing.Any:
        r"""
        X-component bitmask as a Python int.
        """
    @property
    def z(self) -> typing.Any:
        r"""
        Z-component bitmask as a Python int.
        """
    @property
    def weight(self) -> builtins.int:
        r"""
        Number of non-identity single-qubit Pauli operators (popcount of x | z).
        """
    def __new__(cls, x: typing.Any, z: typing.Any, n_qubits: builtins.int) -> PauliString:
        r"""
        Construct a Pauli monomial from X and Z bitmasks.
        
        Arguments:
            x: Integer bitmask where bit k is set if qubit k has an X or Y component.
            z: Integer bitmask where bit k is set if qubit k has a Z or Y component.
            n_qubits: Total number of qubits in the system.
        """
    def commutes_with(self, other: PauliString) -> builtins.bool:
        r"""
        Return True if this Pauli string commutes with *other*.
        
        Two Pauli strings commute iff the number of positions where they
        anticommute is even.
        
        Arguments:
            other: Another PauliString to check commutation with.
        
        Returns:
           True if self and other commute, False otherwise.
        """
    def __matmul__(self, other: PauliString) -> tuple[builtins.complex, PauliString]:
        r"""
        Multiply two Pauli strings, returning (phase, product).
        
        The phase factor is in {1, i, -1, -i}. Phase and monomial are returned
        separately so that equal monomials (modulo phase) hash identically.
        """
    def trace_with_fock_state(self, fock_state: typing.Any) -> builtins.float:
        r"""
        Compute $\langle \psi | P | \psi \rangle$ for this Pauli string P.
        
        Returns 0.0 if P has any X or Y components (off-diagonal).
        For Z-only P, returns $(-1)^{\text{popcount}(z \text{ AND } \psi)}$.
        
        Arguments:
            fock_state: Computational basis state as a bitstring integer.
        Returns:
            Expectation value of the Pauli string in the given Fock state.
        """
    def to_bytes(self) -> bytes:
        r"""
        Serialize the monomial as little-endian X bytes concatenated with Z bytes.
        """
    def __hash__(self) -> builtins.int: ...
    def __eq__(self, other: PauliString) -> builtins.bool: ...
    def __repr__(self) -> builtins.str: ...

@typing.final
class PauliSurrogateModel:
    r"""
    Compiled surrogate model for Pauli observables.
    """
    @property
    def n_params(self) -> builtins.int:
        r"""
        Number of parameter indices used by this model.
        """
    @property
    def n_terms(self) -> builtins.int:
        r"""
        Number of compiled terms.
        """
    @property
    def n_monomials(self) -> builtins.int: ...
    def evaluate(self, params: typing.Sequence[builtins.float]) -> builtins.float: ...
    def evaluate_batch(self, param_sets: typing.Sequence[typing.Sequence[builtins.float]]) -> builtins.list[builtins.float]: ...
    def save(self, path: builtins.str) -> None:
        r"""
        Save to a gzip-compressed binary file.
        """
    @staticmethod
    def load(path: builtins.str) -> PauliSurrogateModel:
        r"""
        Load a model from a file produced by `save`.
        """
    def __repr__(self) -> builtins.str: ...

@typing.final
class PauliSurrogatePropagator:
    r"""
    Back-propagates Pauli observables symbolically, producing a compiled model
    that can be re-evaluated for any parameter assignment.
    
    Arguments:
        truncation: A list of truncator objects
            (FrequencyTruncator, CoefficientTruncator, WeightTruncator,
            TermBudget) applied at each flush, a single such truncator, a
            legacy FrequencyTruncationPolicy (decomposed automatically), or None.
        n_threads: Number of worker threads. Defaults to the system thread count.
        logger: Optional Logger for verbose JSON Lines event logging.
    """
    @property
    def truncators(self) -> builtins.list[typing.Any]:
        r"""
        The active truncation pipeline as a list of truncator objects.
        """
    def __new__(cls, truncation: typing.Optional[typing.Any] = None, n_threads: typing.Optional[builtins.int] = None, logger: typing.Optional[typing.Any] = None) -> PauliSurrogatePropagator: ...
    def build(self, observable: PauliTermSum, circuit: typing.Any, initial_state: typing.Optional[typing.Any] = None) -> PauliSurrogateModel:
        r"""
        Compile the observable back-propagated through the circuit into a SurrogateModel.
        
        Arguments:
            observable: The Pauli observable to back-propagate.
            circuit: A SurrogatePauliCircuit.
            initial_state: Fock state as a bitstring integer (default 0).
        """
    def set_truncation(self, truncation: typing.Optional[typing.Any] = None) -> None:
        r"""
        Replace the truncation pipeline (accepts the same forms as the
        constructor's `truncation`).
        """

@typing.final
class PauliTermStreamer:
    @staticmethod
    def from_file(path: builtins.str) -> PauliTermStreamer:
        r"""
        Open a gzip-compressed binary file for lazy streaming.
        
        Arguments:
            path: Path to a file written by `PauliTermSum.save()`.
        """
    def __iter__(self) -> PauliTermStreamer: ...
    def __next__(self) -> typing.Optional[tuple[PauliString, builtins.float]]: ...

class PauliTermSum:
    r"""
    A mutable, weighted sum of Pauli strings with real coefficients.
    
    Arguments:
        terms: Optional initial mapping of PauliString to real coefficient.
        dtype: Coefficient precision, "float64" (default) or "float32".
    """
    @property
    def dtype(self) -> builtins.str:
        r"""
        Coefficient precision: "float64" or "float32".
        """
    @property
    def sparse_key_bytes(self) -> builtins.int:
        r"""
        Bytes of resident sparse key storage held by this term sum.
        
        Keys only: coefficients and merge metadata are excluded.
        """
    def __new__(cls, terms: typing.Optional[dict] = None, dtype: typing.Optional[builtins.str] = None) -> PauliTermSum:
        r"""
        Initialize a Pauli term sum.
        
        Arguments:
            terms: Optional initial mapping of PauliString to real coefficient.
            dtype: Coefficient precision, "float64" (default) or "float32".
        """
    def add(self, term: PauliString, coeff: builtins.float) -> None:
        r"""
        Add *coeff* x *term* to the sum, accumulating if the monomial is already present.
        """
    def scale(self, factor: builtins.float) -> None:
        r"""
        Multiply every coefficient by *factor* in-place.
        """
    def merge(self, other: PauliTermSum) -> None:
        r"""
        Add all terms from *other* into this sum. Both sums must share the same dtype.
        """
    def merge_from_file(self, streamer: PauliTermStreamer) -> None:
        r"""
        Stream terms from a file and merge them into this sum one at a time,
        accumulating coefficients for strings already present. The file is
        always f64; values are cast down if this sum is float32.
        
        Arguments:
            streamer: A PauliTermStreamer opened with PauliTermStreamer.from_file().
        """
    def truncate(self, policy: typing.Any) -> None: ...
    def apply_damping(self, noise: typing.Any, active_modes: builtins.int) -> None:
        r"""
        Apply noise damping to every coefficient.
        """
    def norm_squared(self) -> builtins.float:
        r"""
        Return the sum of |coefficient|^2 over all terms.
        """
    def items(self) -> builtins.list[tuple[PauliString, builtins.float]]:
        r"""
        Return all (monomial, coefficient) pairs.
        """
    def __len__(self) -> builtins.int: ...
    def __setitem__(self, term: PauliString, coeff: builtins.float) -> None: ...
    def __getitem__(self, term: PauliString) -> builtins.float: ...
    def copy(self) -> PauliTermSum:
        r"""
        Return a shallow copy of this term sum.
        """
    @staticmethod
    def from_file(path: builtins.str) -> PauliTermSum:
        r"""
        Load a PauliTermSum from a gzip-compressed binary file saved by `propagate` or
        `expectation_value`. Always loads as float64 (the file format's precision).
        
        Arguments:
            path: Path to the file written by the `filename` parameter.
        """
    def save(self, path: builtins.str) -> None:
        r"""
        Save this term sum to a gzip-compressed binary file. Coefficients are
        always widened to f64 on disk regardless of in-memory precision.
        
        Arguments:
            path: Destination file path.
        """

@typing.final
class PropagationResult:
    @property
    def n_terms(self) -> builtins.list[builtins.int]: ...
    @property
    def expectation_value(self) -> builtins.float: ...
    @property
    def sparse_key_bytes(self) -> builtins.int:
        r"""
        Bytes of resident sparse term keys held by the evolved term sum at the
        end of the run.
        """
    @property
    def terms_below_cutoff(self) -> builtins.int:
        r"""
        Live terms whose magnitude is below the coefficient cutoff.
        """
    def __repr__(self) -> builtins.str: ...

class Simplify:
    @property
    def enabled(self) -> builtins.bool: ...
    @enabled.setter
    def enabled(self, value: builtins.bool) -> None: ...
    def __new__(cls, enabled: builtins.bool = True) -> Simplify: ...
    def __repr__(self) -> builtins.str: ...

class TermBudget:
    r"""
    Term-count budget: `max_terms` triggers a truncation pass once the live
    term count reaches it; `min_terms` is the count below which lossy operators
    are suppressed. Applies to both propagators. Either field `None` disables
    that bound.
    """
    @property
    def max_terms(self) -> typing.Optional[builtins.int]: ...
    @max_terms.setter
    def max_terms(self, value: typing.Optional[builtins.int]) -> None: ...
    @property
    def min_terms(self) -> typing.Optional[builtins.int]: ...
    @min_terms.setter
    def min_terms(self, value: typing.Optional[builtins.int]) -> None: ...
    def __new__(cls, max_terms: typing.Optional[builtins.int] = None, min_terms: typing.Optional[builtins.int] = None) -> TermBudget: ...
    def __repr__(self) -> builtins.str: ...

class TruncationPolicy:
    r"""
    Controls when and how terms are discarded during propagation.
    
    Arguments:
        weight_cutoff: Discard terms with Pauli weight strictly greater than this value.
            None disables weight-based truncation.
        coeff_cutoff: Discard terms with |coefficient| strictly less than this value.
        truncation_range: (min_terms, max_terms) pair. Truncation fires when the term
            count reaches max_terms and will not reduce it below min_terms.
            Defaults to (None, $10^7$).
    """
    @property
    def weight_cutoff(self) -> typing.Optional[builtins.int]: ...
    @weight_cutoff.setter
    def weight_cutoff(self, value: typing.Optional[builtins.int]) -> None: ...
    @property
    def coeff_cutoff(self) -> builtins.float: ...
    @coeff_cutoff.setter
    def coeff_cutoff(self, value: builtins.float) -> None: ...
    @property
    def truncation_range(self) -> tuple[typing.Optional[builtins.int], typing.Optional[builtins.int]]:
        r"""
        The (min_terms, max_terms) pair controlling when and how aggressively truncation fires.
        """
    @truncation_range.setter
    def truncation_range(self, value: tuple[typing.Optional[builtins.int], typing.Optional[builtins.int]]) -> None: ...
    def __new__(cls, weight_cutoff: typing.Optional[builtins.int] = None, coeff_cutoff: builtins.float = 0.0, truncation_range: typing.Optional[tuple[typing.Optional[builtins.int], typing.Optional[builtins.int]]] = None) -> TruncationPolicy:
        r"""
        Initialize the truncation policy.
        
        Arguments:
            weight_cutoff: Discard terms with Pauli weight strictly greater than this value.
            coeff_cutoff: Discard terms with |coefficient| strictly less than this value.
            truncation_range: (min_terms, max_terms) pair. Truncation is triggered when the
                term count reaches max_terms and will not reduce it below min_terms.
        """
    def should_truncate(self, weight: builtins.int, abs_coeff: builtins.float) -> builtins.bool:
        r"""
        Return True if a term with *weight* and |coefficient| *abs_coeff* should be discarded.
        """

class UniformNoiseModel:
    r"""
    Exponential damping noise: each term of weight w is scaled by $\exp(-\gamma w)$, where $w$ is the term's Pauli weight.
    
    Arguments:
        damping: Damping rate $\gamma$.
    """
    @property
    def damping(self) -> builtins.float: ...
    @damping.setter
    def damping(self, value: builtins.float) -> None: ...
    def __new__(cls, damping: builtins.float) -> UniformNoiseModel:
        r"""
        Initialize the uniform noise model.
        
        Arguments:
            damping: Per-weight damping rate $\gamma$. Each term is multiplied by $\exp(-\gamma w)$.
        """
    def damping_factor(self, term_weight: builtins.int, active_modes: builtins.int) -> builtins.float:
        r"""
        Return $\exp(-\gamma w)$: the multiplicative factor applied to a term's coefficient.
        
        Arguments:
            term_weight: Pauli weight of the term.
            active_modes: Unused for uniform noise; present for API compatibility.
        """
    def apply_noise(self, term_sum: typing.Any) -> None:
        r"""
        Apply uniform damping to all terms in *term_sum* in-place.
        
        Arguments:
            term_sum: A MajoranaTermSum or PauliTermSum to damp in-place.
        """

class WeightTruncator:
    r"""
    Drop whole Pauli/Majorana terms whose operator weight exceeds `weight`.
    Applies to both propagators.
    
    A term with weight `w` is exponentially unlikely in `w` to
    contribute to the final state, which is why this is a useful
    truncation criterion for larger circuits!
    """
    @property
    def weight(self) -> typing.Optional[builtins.int]: ...
    @weight.setter
    def weight(self, value: typing.Optional[builtins.int]) -> None: ...
    def __new__(cls, weight: typing.Optional[builtins.int] = None) -> WeightTruncator: ...
    def __repr__(self) -> builtins.str: ...

def hybrid_expectation(observable: PauliTermSum, mps_arrays: typing.Sequence[numpy.typing.NDArray[numpy.complex128]]) -> builtins.float:
    r"""
    Computes $\sum_i c_i \langle\Psi|P_i|\Psi\rangle$ over every term in `observable`,
    given $|\Psi\rangle$ as a list of MPS site tensors (each rank-3, shape
    `(bond_left, 2, bond_right)`, with dummy size-1 bonds at the open
    boundaries
    
    Arguments:
        observable: A Heisenberg-propagated `PauliTermSum` (e.g. the result
            of `PauliPropagator.propagate(observable, circuit1)`).
        mps_arrays: $|\Psi\rangle$'s site tensors in left-to-right qubit order,
            complex128, rank-3, contiguous.
    """

def rust_available() -> builtins.bool: ...

