[package]
name = "propaq"
version = "0.1.0"
edition = "2021"

[lib]
name = "_rust_core"
crate-type = ["cdylib"]

[dependencies]
propaq-core = { path = "../core" }
propaq-majorana = { path = "../majorana" }
propaq-pauli = { path = "../pauli" }
propaq-surrogate = { path = "../surrogate" }
pyo3 = { version = "0.23", features = ["extension-module", "num-complex"] }
mimalloc = "0.1.52"
