[package]
name = "propaq"
version = "0.1.2"
edition = "2021"

[lib]
name = "_rust_core"
crate-type = ["cdylib", "rlib"]

[features]
default = []
extension-module = ["pyo3/extension-module"]

[dependencies]
propaq-core = { path = "../core" }
propaq-majorana = { path = "../majorana" }
propaq-pauli = { path = "../pauli" }
propaq-surrogate = { path = "../surrogate" }
propaq-hybrid = { path = "../hybrid" }
pyo3 = { version = "0.27", features = ["num-complex"] }
pyo3-stub-gen = "0.23"
