[package]
name = "propaq"
version = "0.1.0"
edition = "2021"

[lib]
name = "_rust_core"
crate-type = ["cdylib"]

[dependencies]
propaq-core = { path = "../propaq-core" }
propaq-majorana = { path = "../propaq-majorana" }
propaq-pauli = { path = "../propaq-pauli" }
propaq-mps = { path = "../propaq-mps" }
pyo3 = { version = "0.23", features = ["extension-module", "num-complex"] }
